words = ["BEEP", "DART", "CORE", "FROG", "HEAT", "MOLD", "WORK",
 "AVAIL", "CAMEL", "EARTH", "GIANT", "KARMA", "MOULD", "NINJA", 
 "ANTHEM", "BREATH", "CRAYON", "ZODIAC", "TRAVEL", 
 "AIRPORT", "BOILING", "CLUSTER", "UPTIGHT", "TOURISM"]